# Generated by Django 2.0 on 2021-03-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('null_test', models.CharField(max_length=200, null=True)),
                ('blank_test', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
